apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: cloudpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.51.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: cloudpulse
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cloudpulse
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'cloudpulse-auth-service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['auth-service:8001']

      - job_name: 'cloudpulse-order-service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['order-service:8002']

      - job_name: 'cloudpulse-inventory-service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['inventory-service:8003']
