apiVersion: v1
kind: Secret
metadata:
  name: cloudpulse-secrets
  namespace: cloudpulse
type: Opaque
stringData:
  JWT_SECRET: "super-secret-cloudpulse-key-change-in-production-32bytes"
  POSTGRES_PASSWORD: "cloudpulse_password"
  AUTH_DB_URL: "postgresql://cloudpulse:cloudpulse_password@postgres:5432/auth_db"
  ORDER_DB_URL: "postgresql://cloudpulse:cloudpulse_password@postgres:5432/order_db"
  INVENTORY_DB_URL: "postgresql://cloudpulse:cloudpulse_password@postgres:5432/inventory_db"
