import asyncio
import httpx
from prometheus_client import Gauge, start_http_server
from ml.ingestion.prometheus_client import PrometheusMetricsIngestor
from ml.inference.detector import AnomalyDetector
from shared.config.settings import settings
from shared.logging import get_logger

logger = get_logger("ml-anomaly-service")

# Prometheus Gauge for Grafana visualization & Remediation Triggering
ML_ANOMALY_SCORE = Gauge(
    "cloudpulse_ml_anomaly_score",
    "Real-time ML Anomaly Score generated by Isolation Forest (0.0 to 1.0)",
    ["target_service"]
)

TARGET_SERVICES = ["auth-service", "order-service", "inventory-service"]
REMEDIATION_CONTROLLER_URL = "http://localhost:8004/remediation/alert"


class AnomalyDetectionService:
    def __init__(self):
        self.ingestor = PrometheusMetricsIngestor()
        self.detector = AnomalyDetector()

    async def run_detection_loop(self, interval_seconds: int = 5):
        """
        Continuously evaluate microservices metrics and publish anomaly scores.
        """
        logger.info(f"Starting ML Anomaly Detection Service loop (Interval: {interval_seconds}s)...")
        while True:
            for service in TARGET_SERVICES:
                try:
                    features = await self.ingestor.extract_service_features(service)
                    score, is_anomaly = self.detector.predict_anomaly(features)

                    # Update Prometheus gauge
                    ML_ANOMALY_SCORE.labels(target_service=service).set(score)

                    if is_anomaly:
                        logger.warning(
                            f"🚨 ANOMALY DETECTED for {service}! Score: {score:.2f}. "
                            f"Metrics: Latency={features.get('latency_mean'):.3f}s, "
                            f"ErrorRate={features.get('error_rate'):.1%}"
                        )
                        # Notify Remediation Controller
                        await self.notify_remediation_controller(service, score, features)
                    else:
                        logger.debug(f"Service {service} operational baseline normal (Score: {score:.2f})")

                except Exception as exc:
                    logger.error(f"Error in anomaly detection loop for {service}: {exc}")

            await asyncio.sleep(interval_seconds)

    async def notify_remediation_controller(self, service: str, score: float, metrics: dict):
        """
        Send HTTP alert POST request to Remediation Controller.
        """
        payload = {
            "target_service": service,
            "anomaly_score": score,
            "metrics": metrics
        }
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                await client.post(REMEDIATION_CONTROLLER_URL, json=payload)
        except Exception as e:
            logger.debug(f"Remediation controller alert dispatch (offline / async): {e}")


if __name__ == "__main__":
    # Expose Prometheus exporter on port 9091
    start_http_server(9091)
    logger.info("ML Anomaly Detection Prometheus exporter listening on port 9091")
    
    service = AnomalyDetectionService()
    asyncio.run(service.run_detection_loop())
